### ISSUE TITLE
Anonymous Dependency

### ISSUE THREAD

**Issue by Ikabodo** [matthewbstroud/stroud-dnd-helpers#118]
Love the macros in this mod, super useful. 

Question. Would it be possible to put the dependency of things like Anonymous as optional? 

We don't really need that part and the mod is a hard dependency for now. And unfortunately the anonymous mod has no setting to disable it.

**Comment by matthewbstroud** [comment]
That is a reasonable request.  I will look into it.  Which features do you
use the most?

**Comment by matthewbstroud** [comment]
Fixed in https://github.com/matthewbstroud/stroud-dnd-helpers/pull/119
