### ISSUE TITLE
Weird Patching bug/feature

### ISSUE THREAD

**Issue by Bryn1701** [matthewbstroud/stroud-dnd-helpers#158]
Hi there. I installed your module today and when I logged in it gave a message in chat:

Patching mount for Ivy Wilddew...Patch successful!

What this did was put an active effect on the Druid. It says the source is the Cloak of Useful Items. I am not sure what is going on here. Thanks in advance!
<img width="737" alt="0dba562c09c026a4bf42ac08abfeb918" src="https://github.com/user-attachments/assets/70e08402-74b3-4427-a67b-e214eb3d1b32">
<img width="674" alt="d2922211d69817fdca208655a873a0e6" src="https://github.com/user-attachments/assets/ef9806c1-b87e-4501-a5e9-5322ebea7e22">

**Comment by matthewbstroud** [comment]
I will get a fix in for this today.

**Comment by matthewbstroud** [comment]
Can you right click the druid in the actors side bar, export the data, and attach it to this ticket.

**Comment by matthewbstroud** [comment]
@Bryn1701 This should not happen again.  You can just delete the effect off the Cloak of Useful items and it shouldn't get added back.

**Comment by matthewbstroud** [comment]
Patching horses removed in v12.0.2
