### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by DudeAndre** [matthewbstroud/stroud-dnd-helpers#81]
Hi, the mod asks for JB2A non-patron version as dependency, that's a bit weird, it penalizes the patreon users of one of the most popular mod around. Also is advanced macro really required? I understand it's almost deprecated by new Foundry versions.

**Comment by matthewbstroud** [comment]
I will fix that.

**Comment by matthewbstroud** [comment]
My first module, so I guess I am expecting some issues.

**Comment by matthewbstroud** [comment]
Fixed in 11.1.2.   Thanks for reporting.

**Comment by matthewbstroud** [comment]
@DudeAndre I believe the only thing that uses JBA is the Twilight Domain implementation.  It is untested with the full version...
