### ISSUE TITLE
Delete Chat Messages not appearing

### ISSUE THREAD

**Issue by ravingdragoon** [matthewbstroud/stroud-dnd-helpers#83]
The Delete Chat Messages macro is not appearing in my macros? Has it been removed?

**
![image](https://github.com/matthewbstroud/stroud-dnd-helpers/assets/72875320/f8c58487-7eca-451d-9455-6e30cb89b4ef)
**

**Comment by matthewbstroud** [comment]
It is called Prune Chat log.  When you click that macro, it gives two options: 
![image](https://github.com/matthewbstroud/stroud-dnd-helpers/assets/17620888/b03edb26-fec3-4c09-a12e-0130b45913a9)

**Comment by matthewbstroud** [comment]
I need better documentation, but that one macro does both.  I was trying to save hotbar slots.

**Comment by matthewbstroud** [comment]
I will update the readme to this
# Utility Macros
- **Chat**
  - **Prune Chat Log**: Click to gain access to two options
    - **Remove Recent Messages**:  Delete messages that were created less than a specified number of minutes ago.  (Defaults to 30)
    - **Remove Old Messages**: Delete messages older than a specified number of days. (Defaults to 7)

**Comment by ravingdragoon** [comment]
Awesome! Thank you :)
