### ISSUE TITLE
Adhoc damage

### ISSUE THREAD

**Issue by YenBenGrey** [matthewbstroud/stroud-dnd-helpers#97]
Hello there, 

I have used adhoc damage for some time now however with the recent problem with Warpgate and the fact I am updating to v12 and dnd 3.2.1 is there another way to create the buttons other than Warpgate? 

Line 79 of the macro creates the button dialog via WG. 

It is such an amazing macro.

**Comment by matthewbstroud** [comment]
I am planning to pick up things after the 4th of July.  I will take a look
and let you know.

**Comment by YenBenGrey** [comment]
Thank you, I appreciate your response.

**Comment by matthewbstroud** [comment]
@YenBenGrey  can you test this in v11.2.1?  I have removed warpgate as a dependency.  I haven't really done any module testing in v12 though.

**Comment by YenBenGrey** [comment]
Hi Matthew, 

I am on v12 now, however I have it backed up on 11.315 if you mean Foundry version. 

I cannot find the module on v12 currently to be able to test.

Is 11.315 ok to test on? 

I have to say I only had the AdHoc damage macro part of it.

**Comment by matthewbstroud** [comment]
I have uploaded a new version of my module, which is 11.2.1.  You can try
it with v12 of foundry.
https://github.com/matthewbstroud/stroud-dnd-helpers/releases/latest/download/module.json

**Comment by YenBenGrey** [comment]
Hello Matthew, 

The module has dependencies that have not and will never be updated to v12 unfortunately. Once such module is Template Macros, Zhell is not updating it for v12.
I use MidiQol DIME instead of Item Macros now. 

Is there a way to just extract the AdHoc damage macro? I am not the greatest when it comes to code. lol

**Comment by matthewbstroud** [comment]
Let me see what I can do to remove the dependency on Template Macros.  I am holding off on upgrading to v12 until the dust settles.

**Comment by matthewbstroud** [comment]
I have removed that and several other dependencies in v11.2.3,
